notifications:
  email: false

sudo: required
language: c

git:
  depth: 1

addons:
    apt:
        config:
            retries: true
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
        packages:
            - gcc-8
            - clang-6.0
            - g++-8
            - libstdc++-8-dev

matrix:
    include:
        - os: linux
          compiler: gcc
          dist: trusty

        - os: linux
          compiler: clang
          dist: trusty

        - os: osx
          compiler: gcc

        - os: osx
          compiler: clang

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update > /dev/null; fi

before_script:
  - eval "${TOOLCHAIN_EVAL}"
  - git clone -b devel --depth 1 git://github.com/nim-lang/Nim.git
  - cd Nim
  - git clone --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$PWD/bin:$PATH
  - cd ..

script:
  - nim c --run tests/test
  - nim --cpu:i386 --passC:-m32 --passL:-m32 c --run tests/test
